#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "etherpad"
name = "Etherpad"
description.en = "Collaborative editing in real-time"
description.fr = "Édition collaborative en temps réel"

version = "0.0.4~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://etherpad.org/"
demo = "https://video.etherpad.com/"
admindoc = "https://etherpad.org/doc/"
code = "https://github.com/ether/etherpad-go"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["arm64", "amd64"]
multi_instance = true

ldap = false
sso = false

disk = "20M"
ram.build = "90M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/etherpad"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["ca", "de", "en", "es", "fr", "gl", "hu", "it", "nl", "pt"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.sources.main]
    rename = "etherpad"
    in_subdir = false
    extract = false
    amd64.url = "https://github.com/ether/etherpad-go/releases/download/v0.0.4/etherpad-go-linux-amd64"
    amd64.sha256 = "fee1c318e7256b40d034f12b910a0f4700b7dc0bcdbb471a5a4eca7316eeef17"
    arm64.url = "https://github.com/ether/etherpad-go/releases/download/v0.0.4/etherpad-go-linux-arm64"
    arm64.sha256 = "69002771b3d70b56364e7da831ba9395a143bbea58d819701f6d6232a0d3ddfc"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "*-amd64"
    autoupdate.asset.armhf = "*-arm64"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "unoconv, libreoffice-writer"
    