#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "etherpad"
name = "Etherpad"
description.en = "Collaborative editing in real-time"
description.fr = "Édition collaborative en temps réel"

version = "2.4.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://etherpad.org/"
demo = "https://video.etherpad.com/"
admindoc = "https://etherpad.org/doc/v2.2.7/"
code = "https://github.com/ether/etherpad-lite"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true

sso = true

disk = "200M"
ram.build = "2G"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/etherpad"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.export]
    ask.en = "Use AbiWord (~260 Mo) or LibreOffice (~400 Mo) (more stable) to expand export possibilities (PDF, doc)?"
    ask.fr = "Utiliser AbiWord (~260 Mo) ou LibreOffice (~400 Mo) (plus stable) pour étendre les possibilités d'export (PDF, doc) ?"
    type = "select"
    choices = ["none", "abiword", "libreoffice"]
    default = "none"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["ca", "de", "en", "es", "fr", "gl", "hu", "it", "nl", "pt"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.sources.main]
    url = "https://github.com/ether/etherpad-lite/archive/refs/tags/2.4.2.tar.gz"
    sha256 = "e6c78f95cde28b9dbe60b52c3b9bacab43d04a4b20e909e9a6b002d63347edca"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]

    [resources.apt]
    packages_from_raw_bash = """
          if [[ "$export" == "libreoffice" ]]
          then
              echo "unoconv libreoffice-writer"
          elif [[ "$export" == "abiword" ]]
          then
              echo "abiword"
          fi
    """
    