test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    args.export = "none"
    args.password = "##SuperAdminPassword##"

    #test_upgrade_from.96653aee9379d579a655777ac274355f4afca61c.name = "Upgrade from 5.4"

    [with_abiword]
    args.export = "abiword"
    only = ["install.root"]

    [with_libreoffice]
    args.export = "libreoffice"
    only = ["install.root"]